### ISSUE TITLE
Code Generation stucks after Flutter 2.0 Upgrade

### ISSUE THREAD

**Issue by LisaLamparter** [gibahjoe/openapi-generator-dart#38]
Hi there,

I'm using the following version of your lib:
dependencies: openapi_generator_annotations: ^2.2.0
dev-dependencies: openapi_generator: ^2.2.0

After upgrading the flutter version to 2.0 the code generations stucks during "flutter pub run build_runner build" with the message
```
[WARNING] Heartbeat:
No actions completed for 15.1s, waiting on:
  - openapi_generator:openapi_generator on lib/repositories/rest/rest_client_config.dart

[INFO] Heartbeat:48.5s elapsed, 179/180 actions completed.
[INFO] Heartbeat:49.5s elapsed, 179/180 actions completed.
[INFO] Heartbeat:50.5s elapsed, 179/180 actions completed.
[INFO] Heartbeat:51.6s elapsed, 179/180 actions completed.
```

I am using this generator: **Generator.dio**

Any ideas how to solve this? Is there any working version in the pipeline that I can try?

Thanks in advance,
L.

**Comment by petrleocompel** [comment]
This is not only for `Flutter 2.0` it's also on older version. Can confirm.

**Comment by gibahjoe** [comment]
Hi, you can try overriding the dependencies in the `pub spec` and adding it to `.openapi-generator-ignore` so that it doesn't get overwritten in next generation

In pubspec.yaml,

```dart
dependency_overrides:
    analyzer: 1.0.0
```

At the end of .openapi-generator-ignore, add the pubspec
```
pubspec.yaml
```

**Comment by Abhilash-Chandran** [comment]
Same issue here. Suggested option overriding analyzer version didn't help either.  😞 Would you recommend any other option.? I don't see any errors to even post them here. builder just keeps waiting on the generator dart file.

**Comment by petrleocompel** [comment]
I guess ideal will be to wait on OpenAPITools/openapi-generator#8869 which will provide support  and solve this dependency problem.

I already tried it (compiled from source of forked repo) and worked really well.

I guess OpenAPITools/openapi-generator#8869 needs to be done first then here can be issue solved by updating dependency and defining new config / type of generator for Flutter 2

**Comment by gibahjoe** [comment]
> Same issue here. Suggested option overriding analyzer version didn't help either. 😞 Would you recommend any other option.? I don't see any errors to even post them here. builder just keeps waiting on the generator dart file.
> 
> flutter doctor summary
> ```
> 
> Doctor summary (to see all details, run flutter doctor  
> -v):
> [√] Flutter (Channel stable, 2.0.2, on Microsoft Windows    [Version 10.0.18363.1379], locale de-DE)
> [√] Android toolchain - develop for Android devices     
>     (Android SDK version 29.0.3)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio  
>     Community 2019 16.7.6)
> [√] Android Studio (version 4.1.0)
> [√] VS Code (version 1.54.3)
> [√] Connected device (2 available)
> 
> • No issues found!
> ```

Thats odd. My suggestion is exactly what works for me. I use same generator too.

Can you post the pubspec of the generated code and also your project pubspec?

**Comment by gibahjoe** [comment]
> Hi, you can try overriding the dependencies in the `pub spec` and adding it to `.openapi-generator-ignore` so that it doesn't get overwritten in next generation
> 
> In pubspec.yaml,
> 
> ```yaml
> dependency_overrides:
>     analyzer: 1.0.0
> ```
> 
> At the end of .openapi-generator-ignore, add the pubspec
> 
> ```
> pubspec.yaml
> ```

If I wasn't clear, This should be done in the generated code

Step 1: configure the @Openapi annotation to skip source gen by setting `runSourceGenOnOutput` and `fetchDependencies` to `false`.
Step 2: run source gen to generate the api package.
Step 3: Apply changes mentioned above to the generated code.
Step 4: Also apply the dependency_overrides to your project's pubspec
Step 4: run source gen again

Please let me know if this steps I mentioned are not clear.

This is a workaround until the guys at OpenApi tools resolve all issues.

**Comment by gibahjoe** [comment]
Also, Please update to version 3.0.2

**Comment by Abhilash-Chandran** [comment]
@gibahjoe Thanks a lot for your suggestions. I already tried directly manipulating the versions of dio and other to nullsafe versions in the generated pubspec and still faced issues with generated code targeting @dart=2.6. 

I will check out your suggestions if it works for me. But nevertheless the null safe version of code generation is not in place if I understand correctly. As @petrleocompel suggested, I feel we need wait until its fixed.

**Comment by Abhilash-Chandran** [comment]
Now I see https://github.com/OpenAPITools/openapi-generator/pull/8869 is already merged.

**Comment by gibahjoe** [comment]
Yes. I saw that late yesterday. I will release an updated version sometime this week.

**Comment by ILAgent** [comment]
Hello! What about update?
#41

**Comment by gibahjoe** [comment]
version 3.1.* has been released

**Comment by gibahjoe** [comment]
Closing this because no clear next steps. Feel free to reopen
